// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actions': string;
  'approved': string;
  'badges': string;
  'blocklistButton': string;
  'buttons': string;
  'card': string;
  'content': string;
  'detailSection': string;
  'details': string;
  'formats': string;
  'grabError': string;
  'history': string;
  'list': string;
  'metadata': string;
  'rejected': string;
  'rejectionPreview': string;
  'releaseTitle': string;
  'row': string;
  'score': string;
}
export const cssExports: CssExports;
export default cssExports;
