// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'button': string;
  'iconPill': string;
  'label': string;
  'navigation': string;
}
export const cssExports: CssExports;
export default cssExports;
