// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backdrop': string;
  'body': string;
  'content': string;
  'header': string;
  'sheet': string;
}
export const cssExports: CssExports;
export default cssExports;
