// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentBody': string;
  'contentBodyContainer': string;
  'errorMessage': string;
  'pageContentBodyWrapper': string;
  'pathFilter': string;
  'pathFilterCount': string;
  'pathFilterLabel': string;
  'pathFilterPicker': string;
  'postersInnerContentBody': string;
  'tableInnerContentBody': string;
}
export const cssExports: CssExports;
export default cssExports;
