// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'currentFile': string;
  'heading': string;
  'job': string;
  'mode': string;
  'modes': string;
  'panel': string;
  'progress': string;
  'results': string;
}
export const cssExports: CssExports;
export default cssExports;
